Word network
maxodsbjerg/NewspaperAPIShiny pull request #14
Opened 2023-08-11 12:05 UTC by maxodsbjerg

2023-08-13 18:12 UTC, VictorHarbo requested changes
One minor comment

2023-08-13 18:12 UTC, VictorHarbo commented on URLDemonstrationAPP/app.R
> +      geom_node_point(color = "#FFFFF0", size = 3) +
I think some code here is deprecated. I got this warning when running the app: 

Warning: Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` in the `default_aes` field and elsewhere instead.

Could you please change this?

2023-08-24 12:31 UTC, maxodsbjerg commented on URLDemonstrationAPP/app.R
> +      geom_node_point(color = "#FFFFF0", size = 3) +
Can't really reproduce this warning?

2023-08-24 12:35 UTC, VictorHarbo approved these changes

2023-08-24 13:03 UTC, merged